# Generated by Django 4.2.1 on 2023-05-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole1', models.IntegerField()),
                ('pole2', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.AlterModelOptions(
            name='model1',
            options={'verbose_name': 'модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AddField(
            model_name='model1',
            name='pole3',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
