# Generated by Django 4.2.1 on 2023-05-25 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitel', '0002_model2_alter_model1_options_model1_pole3'),
    ]

    operations = [
        migrations.AddField(
            model_name='model2',
            name='pole3',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='sitel.model1'),
            preserve_default=False,
        ),
    ]
