# Generated by Django 4.2.1 on 2023-05-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitel', '0003_model2_pole3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='pole3',
        ),
    ]
