# Generated by Django 4.2.1 on 2023-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitel', '0005_model2_pole3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='pole3',
        ),
        migrations.AddField(
            model_name='model2',
            name='pole4',
            field=models.ManyToManyField(to='sitel.model1'),
        ),
    ]
